import Head from "next/head";
import Navbar from "../../components/Navbar";
import TinderCard from "react-tinder-card";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  const routes = require("../assets/routes.json");
  const mockdata = require("../assets/content/mock_cards.json");
  function onSwipe(direction){
    console.log(direction);
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="cards">
        {mockdata.map((data, index)=>{
            return (
                <TinderCard key={index} className="card" flickOnSwipe={true} onSwipe={onSwipe}>
                    <div>
                        <h3>{data.activity}</h3>
                        <ul>
                            {data.badges.split(',').map((badge)=>{
                                <li>{badge}</li>
                            })}
                        </ul>
                        <img className="card__image" src={data.image}></img>
                        <Link href={data.url}>{data.service}</Link>
                    </div>
                </TinderCard>
            )
        })}
      </div>
    </div>
  );
}
