import Head from "next/head";
import Navbar from "../../components/Navbar";
import styles from "../../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  const routes = require("../assets/routes.json");
  const listOfGames = require("./routes.json");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {listOfGames.map((item, index) => {
        return (
          <div key={index}>
            <Link href={item.href} key={index}>
              <a className="link">
                {item.label}
              </a>
            </Link>
          </div>
        );
      })}

      <Navbar routes={routes}></Navbar>
    </div>
  );
}
