import Head from "next/head";
import Navbar from "../components/Navbar";
import Palette from "../components/Palette";
import styles from "../styles/Home.module.css";

export default function Home() {
  const routes = require("./assets/routes.json");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Palette/>

      <Navbar routes={routes}></Navbar>
    </div>
  );
}
